DATASET:
  root_dataset: "data/"
  list_train: ["./data/agri-trn.odgt"]
  list_val: "./data/agri-val.odgt"
  # list_train: ["./data/agri-debug.odgt"]
  num_class: 7
  segm_downsampling_rate: 1.0

MODEL:
  arch: "deeplab"
  os: 16
  backbone: "resnet101"
  ibn_mode: "none"
  num_low_level_feat: 3

LOSS:
  dice: 1.0
  focal: 1.0

TRAIN:
  num_epoch: 15
  batch_size_per_gpu: 6
  lr: 0.01
  beta1: 0.9
  weight_decay: 5e-4
  workers: 3
  disp_iter: 20
  seed: 304

VAL:
  batch_size_per_gpu: 6

TEST:
  result: "./"

DIR: "ckpt/"
